spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/barbearia?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
